// The Agentic Crew — EPUB source. GENERATED by scripts/build-epub-source.py from book-crew.typ.
// Do not edit by hand; edit book-crew.typ and re-run the script.

#set text(lang: "en")

_To everyone who was told "you're not technical enough." You are. You always were. Now the tools agree._

= A Note Before We Start

This book is a companion to _The Agentic Crew: Engineering in the Age of AI Agents_. That book was written for software engineers — people who write code for a living. This one is for everyone else who's good with computers.

You might be a project manager, a designer, a sysadmin, a data analyst, a small business owner, or just the person in your family who fixes the Wi-Fi. You live in spreadsheets, manage inboxes like a general, and have forty-seven browser tabs open right now. But you've never written a line of code — and you don't need to.

AI agents are changing how software gets built. That affects you, whether you're working alongside developers, running a business that depends on software, or just trying to understand what's happening to the world around you. The ideas in this book are real. We've simplified the technical details, but we haven't watered them down.

By the end, you'll understand what agents actually are, how modern software works under the hood, and — most importantly — how to direct an agent to build something real. No programming required.

_Rasmus Bornhøft Schlünsen_ — _March 2026_




= A Note on the Second Edition

The first edition of this guide came out in March 2026. Six months later, the engineering edition got a thorough second edition — and this guide gets one alongside it, because most of what changed matters just as much to you as it does to the engineers.

Chat assistants grew hands: the tools you use in a browser can now plug straight into your email, your documents, and your calendar. Agents that used to need a developer's terminal now run in the cloud and hand back finished work. And a new kind of risk went from curiosity to headline: text that _gives your agent orders_, hidden in the emails, web pages, and documents it reads on your behalf.

Here's what's new in this edition:

- *A new chapter, "Hidden Instructions"* — what prompt injection is, why it matters most to people whose agents read inboxes and documents, and the simple three-question check that keeps you out of trouble.
- *Keeping the workbench tidy* — why long conversations get worse, when to start fresh, and how to write your standing instructions down once instead of repeating them every time.
- *Plan before you build* — asking the agent for a plan, and reading it, is the cheapest review you'll ever do.
- *Agents that work while you're away* — what cloud and background agents are, and why the hard part is now reviewing their work, not getting it done.
- *Getting Started brought up to date*, with the specific tools and prices moved there so the rest of the book ages better.
- *Corrections and a new war story* in "When Things Go Wrong".

What didn't change is the core: clear instructions, the right context, healthy scepticism, and your judgement. If anything, the last six months made those matter more.

_Rasmus Bornhøft Schlünsen_ — _September 2026_

= Part I · Setting Sail

_What's changing, and why it matters to you._

#include "chapters/crew/01-welcome-to-the-crew.typ"
#include "chapters/crew/02-the-ground-is-shifting.typ"
= Part II · Below Deck

_How modern software works, and what an agent really is._

#include "chapters/crew/03-whats-under-the-hood.typ"
#include "chapters/crew/04-what-is-an-agent.typ"
= Part III · Taking the Helm

_Instructions, context, trust, reach — and the risks that come with it._

#include "chapters/crew/05-how-to-give-good-instructions.typ"
#include "chapters/crew/06-what-the-agent-can-see.typ"
#include "chapters/crew/07-the-trust-gradient.typ"
#include "chapters/crew/08-extending-the-crews-reach.typ"
#include "chapters/crew/08b-hidden-instructions.typ"
= Part IV · Underway

_Building something real, keeping it safe, and putting agents to work beyond code._

#include "chapters/crew/11-building-something-real.typ"
#include "chapters/crew/09-the-padlock.typ"
#include "chapters/crew/12-building-something-else.typ"
= Part V · Hard-Won Lessons

_Mistakes, restraint, your role, and where to go from here._

#include "chapters/crew/12-when-things-go-wrong.typ"
#include "chapters/crew/13-when-to-do-it-yourself.typ"
#include "chapters/crew/14-being-the-human-in-the-loop.typ"
#include "chapters/crew/15-talking-to-your-tech-team.typ"
#include "chapters/crew/16-keeping-your-finger-on-the-pulse.typ"
#include "chapters/crew/18-getting-started.typ"
#include "chapters/crew/17-final-words.typ"
