#!/usr/bin/env python3
"""Write video/youtube-videos.md: copy-paste upload metadata for every chapter film from 03 on.

Sources: video/meta/<ch>.json (title, youtube_title, description, tags — written by the film agents),
video/narration/<ch>.json and video/build/<ch>/timing.json (for chapter timestamps).
Timestamps are the beat starts; each label is the beat's opening words, trimmed. Re-run after re-voicing a film.
"""
import json, re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
V = ROOT / "video"
ORDER = [f"ch{n:02d}" for n in range(3, 20)] + ["chA", "chB"]
SITE = "https://theagenticcrew.com"


def mmss(t):
    return f"{int(t // 60)}:{int(t % 60):02d}"


STOP = {"a", "an", "the", "and", "or", "of", "to", "in", "on", "with", "that", "is", "it", "its", "has", "for", "but", "so", "then", "as", "at", "by", "from"}


def label(text, n=6):
    """A chapter-marker label: the beat's first clause, at most n words, never ending on a filler word."""
    clause = re.split(r"[.,;:!?]", text.strip())[0]
    words = clause.split()[:n]
    while len(words) > 2 and words[-1].lower() in STOP:
        words.pop()
    return " ".join(words)


def main():
    films = {f["id"]: f for f in json.loads((ROOT / "website/src/data/films.json").read_text())}
    out = ["# YouTube uploads: chapters 3–19 and appendices", "",
           "Generated by `video/tools/youtube_md.py` from the film metadata and narration timings. Chapters 1–2 are in `youtube.md`.",
           "Every video: category Science & Technology · not made for kids · English · **Altered or synthetic content: yes** (AI voice) · end screen over the last 5 s → next film + Subscribe · add to the Part playlist.", ""]
    for ch in ORDER:
        mp, np_, tp = V / "meta" / f"{ch}.json", V / "narration" / f"{ch}.json", V / "build" / ch / "timing.json"
        if not (mp.exists() and np_.exists() and tp.exists()):
            out += [f"## {ch}: not finished yet", ""]
            continue
        meta, narr, timing = json.loads(mp.read_text()), json.loads(np_.read_text()), json.loads(tp.read_text())
        film = films.get(narr["chapter"])
        slug = film["slug"] if film else ""
        master = next((V / "build" / ch).glob(f"{ch}-*.mp4"), None)
        stamps = ["0:00 The Agentic Crew"] + [f"{mmss(timing['beats'][b['id']]['start'])} {label(b['text'])}" for b in narr["beats"]]
        nxt = narr.get("next")
        desc = [meta["description"], "", *stamps, "",
                f"📖 Read it free: {SITE}" + (f"  ·  Watch on the site: {SITE}/watch/{slug}" if slug else "")]
        if nxt:
            desc.append(f"▶ Next: {nxt}")
        desc += ["", "Made by AI agents and steered by the author, Rasmus Bornhøft Schlünsen. Narration: AI voice. Animation: riso-motion (built on ClaudeAnimationBase by John Heibel). Music: \"Hazelwood\"."]
        out += [f"## {narr['chapter']} · {narr['title']}", "",
                f"**File:** `video/build/{ch}/{master.name if master else '?'}` ({mmss(timing['duration'])}) · **Thumbnail:** `video/build/youtube/thumb-{ch}-1280x720.jpg`",
                f"**Title:** `{meta['youtube_title']}`", "", "**Description:**", "", "```", *desc, "```", "",
                f"**Tags:** `{', '.join(meta['tags'])}`", ""]
    (V / "youtube-videos.md").write_text("\n".join(out))
    print(f"wrote video/youtube-videos.md ({sum(1 for c in ORDER if (V / 'meta' / f'{c}.json').exists())} films)")


if __name__ == "__main__":
    main()
