#!/usr/bin/env python3
"""Generate an EPUB source from a PDF entry file so the EPUB mirrors its structure.

Usage: build-epub-source.py [main|crew]   (default: main)
  main: book.typ      -> epub.typ
  crew: book-crew.typ -> epub-crew.typ

pandoc's Typst reader doesn't run the theme's show rules or custom functions,
so this rewrites the PDF-only constructs into plain Typst:
  #part("I", [Title], [Subtitle])  ->  = Part I · Title  + italic subtitle
  #appendix("A", [Title])           ->  = Appendix A · Title
  #heading(... )[Foreword]          ->  = Foreword
The cover, outline, page layout and dedication page are dropped; pandoc builds
the title page, cover and navigation from assets/epub/metadata.yaml.
"""
import re
import sys
from pathlib import Path

EDITIONS = {
    "main": ("book.typ", "epub.typ",
             "To my kids — you're the best crew I've ever had. This whole thing was for you. Always."),
    "crew": ("book-crew.typ", "epub-crew.typ",
             "To everyone who was told \"you're not technical enough.\" You are. You always were. Now the tools agree."),
}
edition = sys.argv[1] if len(sys.argv) > 1 else "main"
src, dst, dedication = EDITIONS[edition]

root = Path(__file__).resolve().parent.parent
book = (root / src).read_text()

# Front matter runs from the first unnumbered heading's section marker to the contents.
first_heading = book.index("#heading(outlined: false")
front = book[book.rfind("// ─── ", 0, first_heading):book.index("// ─── Table of Contents ───")]
front = front.replace("#pagebreak()", "")
front = re.sub(r"#heading\(outlined: false, numbering: none\)\[([^\]]+)\]", r"= \1", front)
front = re.sub(r"#image\([^)]*\)\n", "", front)
front = re.sub(r"#align\(right\)\[\s*(_[^\n]*_) \\\s*(_[^\n]*_)\s*\]", r"\1 — \2", front)
front = re.sub(r"// ─── [^\n]* ───\n", "", front)

body = book[book.index("// ─── Chapters ───"):book.index("// ─── Dedication (End) ───")]
body = re.sub(r'#part\("([^"]*)", \[([^\]]*)\], \[([^\]]*)\]\)',
              lambda m: (f"= Part {m.group(1)} · {m.group(2)}" if m.group(1) else f"= {m.group(2)}") + f"\n\n_{m.group(3)}_\n", body)
body = re.sub(r'#appendix\("([^"]*)", \[([^\]]*)\]\)', r"= Appendix \1 · \2", body)
body = re.sub(r"// ─── [^\n]* ───\n", "", body)

out = f"""// The Agentic Crew — EPUB source. GENERATED by scripts/build-epub-source.py from {src}.
// Do not edit by hand; edit {src} and re-run the script.

#set text(lang: "en")

_{dedication}_

{front.strip()}

{body.strip()}
"""
(root / dst).write_text(out)
print(f"wrote {dst}")
