#!/usr/bin/env python3
"""Generate epub.typ from book.typ so the EPUB mirrors the PDF's structure.

pandoc's Typst reader doesn't run the theme's show rules or custom functions,
so this rewrites the PDF-only constructs into plain Typst:
  #part("I", [Title], [Subtitle])  ->  = Part I · Title  + italic subtitle
  #appendix("A", [Title])           ->  = Appendix A · Title
  #heading(... )[Foreword]          ->  = Foreword
The cover, outline, page layout and dedication page are dropped; pandoc builds
the title page, cover and navigation from assets/epub/metadata.yaml.
"""
import re
from pathlib import Path

root = Path(__file__).resolve().parent.parent
book = (root / "book.typ").read_text()

front = book[book.index("// ─── Foreword ───"):book.index("// ─── Table of Contents ───")]
front = front.replace("#pagebreak()", "")
front = re.sub(r"#heading\(outlined: false, numbering: none\)\[([^\]]+)\]", r"= \1", front)
front = re.sub(r"#image\([^)]*\)\n", "", front)
front = re.sub(r"#align\(right\)\[\s*(_[^\n]*_) \\\s*(_[^\n]*_)\s*\]", r"\1 — \2", front)
front = re.sub(r"// ─── [^\n]* ───\n", "", front)

body = book[book.index("// ─── Chapters ───"):book.index("// ─── Dedication (End) ───")]
body = re.sub(r'#part\("([^"]*)", \[([^\]]*)\], \[([^\]]*)\]\)',
              lambda m: (f"= Part {m.group(1)} · {m.group(2)}" if m.group(1) else f"= {m.group(2)}") + f"\n\n_{m.group(3)}_\n", body)
body = re.sub(r'#appendix\("([^"]*)", \[([^\]]*)\]\)', r"= Appendix \1 · \2", body)
body = re.sub(r"// ─── [^\n]* ───\n", "", body)

out = f"""// The Agentic Crew — EPUB source. GENERATED by scripts/build-epub-source.py from book.typ.
// Do not edit by hand; edit book.typ and re-run the script.

#set text(lang: "en")

_To my kids — you're the best crew I've ever had. This whole thing was for you. Always._

{front.strip()}

{body.strip()}
"""
(root / "epub.typ").write_text(out)
print("wrote epub.typ")
